[package]
name = "encoder"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = "2.0"  
tokio = { version = "1.0", features = ["full", "macros"] }
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
bytes = "1.1"